version: '3.9'
services:
  discord_bot:
    image: nikkyai/twitch-announcement-discord-bot:dev
    environment:
      BOT_TOKEN: "$BOT_TOKEN"
      TWITCH_CLIENT_ID: "$TWITCH_CLIENT_ID"
      TWITCH_CLIENT_SECRET: "$TWITCH_CLIENT_SECRET"
      CONFIG_DIR: /data
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - ./data:/data
      - ./logs:/logs